CREATE TABLE user (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL);
CREATE TABLE sandwiches (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	uid INT NOT NULL,
	name varchar(15),
	FOREIGN KEY (uid)
	REFERENCES user(id)
	ON DELETE CASCADE);
CREATE TABLE likes (
	sid INT NOT NULL,
	FOREIGN KEY (sid)
	REFERENCES sandwiches(id),	
	uid INT NOT NULL,
	FOREIGN KEY (uid)
	REFERENCES user(id),
	UNIQUE(sid, uid));
CREATE TABLE ingredients (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name varchar(15));
CREATE TABLE SandwichIngredient (
	sid INT NOT NULL,
	Iid INT NOT NULL,
	FOREIGN KEY (sid)
	REFERENCES sandwiches(id),	
	FOREIGN KEY (Iid)
	REFERENCES ingredients(id));
